let message1 = prompt("Введите ваше имя")
alert("Привет, " + message1)
console.log(message1)
let message3 = prompt("Для регистации напиши свою почту")
console.log(message3)
let message2 = prompt("ОШИБКА!!! На вашей почте обнаружен вирус напиши свой пароль!")
alert("Хаха неудачник теперь я знаю твою почту и пароль")
console.log(message2)
let message4 = prompt("Если хочешь веруть напиши верни пожалуста")
alert("Ну хорошо, больше вводи в подзрительные сайты свои данные")
console.log(message4)
alert("Пока!!")
console.log(message5)